version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: lab5-postgres
    restart: always
    environment:
      POSTGRES_DB: lab5
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Lab5.Api/Dockerfile
    container_name: lab5-api
    depends_on:
      - postgres
    environment:
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=lab5;Username=postgres;Password=postgres
    ports:
      - "5000:8080"

volumes:
  postgres_data: