version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: lab5_postgres
    environment:
      POSTGRES_DB: lab5db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Lab5.Api/Dockerfile
    container_name: lab5_api
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"

volumes:
  postgres_data: